In [11]:
import pandas as pd

df = pd.read_csv("/remote/unity/bgc-output/DELAIGUE/SOCAT-FLOATS-OSSE/MODEL_FLOATS_v2/processing_steps/BGC-Argo_SO_clean_MLD_monthly_regridded_SLA.csv")

In [12]:
df

,month_center,lat_center,lon_center,depth,MLD,ARMOR3D_temperature,ARMOR3D_salinity,FLOATS_pco2_median,FLOATS_pco2_error_median,FLOATS_temperature_median,FLOATS_salinity_median,FLOATS_count,sla_median
0,2023-02-01,-77.5,-170.5,0.0,29.25,-0.7145,34.2135,382.802002,37.895000,-1.222001,34.122646,4.0,0.077275
1,2023-11-01,-77.5,-170.5,0.0,17.50,-1.7990,34.2175,427.435501,34.321999,-1.651704,34.394283,2.0,0.022325
2,2023-12-01,-77.5,-170.5,0.0,22.60,-0.3015,34.2680,356.127502,41.786999,-0.897576,34.370581,6.0,0.080950
3,2024-01-01,-77.5,-170.5,0.0,20.00,0.3345,34.1670,363.734009,39.803499,-0.230904,34.226492,6.0,0.057200
4,2024-02-01,-77.5,-170.5,0.0,35.65,-0.6200,34.0770,384.696487,38.019501,-0.615187,34.235912,6.0,0.121350
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39985,2020-07-01,-30.5,158.5,0.0,75.95,20.9330,35.6800,377.696991,32.207001,19.764999,35.674915,1.0,0.119350
39986,2020-08-01,-30.5,159.5,0.0,99.85,20.3120,35.6720,385.790985,31.524000,21.070784,35.698017,1.0,0.226050
39987,2020-09-01,-30.5,160.5,0.0,67.55,19.6310,35.7160,368.500488,30.045250,19.768353,35.724983,2.0,0.096200
39988,2020-10-01,-30.5,160.5,0.0,36.90,20.8310,35.7030,371.906006,30.205999,20.082758,35.729160,1.0,0.104900
39989,2024-11-01,-30.5,172.5,0.0,18.60,20.3300,35.7220,386.671997,27.058001,20.287560,35.694969,1.0,0.105575

In [25]:
import pandas as pd

indep_data_path = "/remote/unity/bgc-output/DELAIGUE/SOCAT-FLOATS-OSSE/MODEL_FLOATS_v2/processing_steps/independent_validation/pco2_independent_validation_data_TSMLD_SLA_RRS_PAR_WIND_ATM_CO2_feature_engineered_monthly_1deg.csv"


indep_df = pd.read_csv(indep_data_path)

In [26]:
indep_df

,month_center,lat_center,lon_center,depth,MLD,ARMOR3D_temperature,ARMOR3D_salinity,FLOATS_pco2_median,FLOATS_pco2_error_median,FLOATS_temperature_median,...,month,doy,decimal_year,doy_radians,doy_sin,doy_cos,x_cart,y_cart,z_cart,bottom_depth_m
0,2003-09-01,-35.5,-162.5,0.0,53.45,15.0620,35.2185,339.031494,18.259001,15.380500,...,9,244,2003.665753,4.200266,-0.871706,-0.490029,-0.776436,-0.244809,-0.580703,5426
1,2003-10-01,-35.5,-162.5,0.0,57.25,15.1555,35.1665,336.919983,18.228001,15.775000,...,10,274,2003.747945,4.716693,-0.999991,0.004304,-0.776436,-0.244809,-0.580703,5426
2,2003-08-01,-35.5,-161.5,0.0,93.10,14.6435,35.1210,339.139999,18.066750,15.361249,...,8,213,2003.580822,3.666626,-0.501242,-0.865307,-0.772045,-0.258323,-0.580703,5440
3,2003-09-01,-35.5,-161.5,0.0,68.65,14.9390,35.1900,337.017761,17.990501,15.275500,...,9,244,2003.665753,4.200266,-0.871706,-0.490029,-0.772045,-0.258323,-0.580703,5440
4,2003-10-01,-35.5,-161.5,0.0,37.70,15.3255,35.1340,336.453003,18.209999,15.927500,...,10,274,2003.747945,4.716693,-0.999991,0.004304,-0.772045,-0.258323,-0.580703,5440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1291,2024-01-01,-30.5,-36.5,0.0,23.50,22.6340,35.8940,422.007996,25.484000,22.176453,...,1,1,2024.000000,0.017214,0.017213,0.999852,0.692627,-0.512517,-0.507538,1380
1292,2024-02-01,-30.5,-36.5,0.0,19.30,23.7910,35.7905,429.401001,25.327999,23.560463,...,2,32,2024.084699,0.550855,0.523416,0.852078,0.692627,-0.512517,-0.507538,1380
1293,2024-03-01,-30.5,-36.5,0.0,26.40,24.0830,35.8870,432.535004,25.938999,24.403641,...,3,61,2024.163934,1.050067,0.867456,0.497513,0.692627,-0.512517,-0.507538,1380
1294,2024-04-01,-30.5,-36.5,0.0,40.95,22.9715,36.0405,422.928986,26.481001,22.896458,...,4,92,2024.248634,1.583707,0.999917,-0.012910,0.692627,-0.512517,-0.507538,1380
1295,2024-01-01,-30.5,-35.5,0.0,22.90,22.4820,35.8005,414.153015,27.228001,22.356413,...,1,1,2024.000000,0.017214,0.017213,0.999852,0.701466,-0.500351,-0.507538,824